CREATE DATABASE futebol_db;
USE futebol_db;

CREATE TABLE times (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL
);

CREATE TABLE jogadores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    posicao VARCHAR(30) NOT NULL,
    numero_camisa INT NOT NULL,
    time_id INT,
    FOREIGN KEY (time_id) REFERENCES times(id)
);

CREATE TABLE partidas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    time_casa_id INT NOT NULL,
    time_fora_id INT NOT NULL,
    data_jogo DATE NOT NULL,
    FOREIGN KEY (time_casa_id) REFERENCES times(id),
    FOREIGN KEY (time_fora_id) REFERENCES times(id)
);

-- dados inseridos
INSERT INTO times (nome, cidade) VALUES
('Botafogo', 'Rio de Janeiro'),
('Palmeiras', 'São Paulo'),
('Internacional', 'Porto Alegre'),
('Flamengo', 'Rio de Janeiro'),
('São Paulo', 'São Paulo'),
('Santos', 'São Paulo'),
('Sport', 'Recife'),
('Cruzeiro', 'Belo Horizonte'),
('Bahia', 'Salvador'),
('Ceará', 'Fortaleza'),
('Mirassol', 'Mirassol'),
('Corinthians', 'São Paulo'),
('Vitória', 'Salvador'),
('Vasco', 'Rio de Janeiro'),
('Juventude', 'Caxias do Sul'),
('Grêmio', 'Porto Alegre'),
('Fluminense', 'Rio de Janeiro'),
('Atletico MG', 'Belo Horizonte'),
('Bragantino', 'Bragança Paulista'),
('Fortaleza', 'Fortaleza');

INSERT INTO jogadores (nome, posicao, numero_camisa, time_id) VALUES
('John', 'GOL', 12, 1 ),
('Vitinho', 'ZAG', 2,  1),
('David Ricardo', 'ZAG', 9,  1),
('Alexander Barboza', 'ZAG', 20, 1 ),
('Alex Telles', 'ZAG', 13,  1),
('Danilo', 'MEI', 41,  1),
('Marlon Freitas', 'MEI', 17, 1 ),
('Artur', 'ATA', 7, 1 ),
('Jefferson Savarino', 'ATA', 10, 1 ),
('Matheus Martins', 'ATA', 11, 1 ),
('Santiago Rodríguez', 'ATA', 23, 1 ),
('Weverton', 'GOL', 21,2),
('Agustín Giay', 'LAT', 4,2),
('Bruno Fuchs', 'ZAG', 3, 2),
('Micael', 'ZAG', 13, 2),
('Joaquín Piquerez', 'LAT', 22, 2),
('Aníbal Moreno', 'MEI', 5,2),
('Lucas Evangelista', 'MEI', 30,2),
('Maurício', 'MEI', 18,2),
('Ramón Sosa', 'ATA', 19,2),
('Facundo Torres', 'ATA', 17, 2),
('Vitor Roque', 'ATA', 9,2),
('Anthoni', 'GOL', 24, 3 ),
('Braian Aguirre', 'LAT', 35, 3 ),
('Alan Benítez', 'LAT', 23,3 ),
('Alexandro Bernabei', 'LAT', 26, 3 ),
('Clayton Sampaio', 'ZAG', 20, 3 ),
('Juninho', 'ZAG', 18, 3 ),
('Victor Gabriel', 'ZAG', 41, 3 ),
('Vitão', 'ZAG', 4,  3),
('Bruno Henrique', 'MEI', 8, 3 ),
('Ronaldo', 'MEI', 16, 3 ),
('Johan Carbonero', 'ATA', 7, 3 ),
('Agustín Rossi', 'GOL', 1, 4),
('Guillermo Varela', 'LAT', 2, 4),
('Léo Ortiz', 'ZAG', 3, 4),
('Léo Pereira', 'ZAG', 4, 4),
('Alex Sandro', 'LAT', 26, 4),
('Jorginho', 'MEI', 21, 4),
('Saúl', 'MEI', 8, 4),
('Arrascaeta', 'MEI', 10, 4),
('Gonzalo Plata', 'ATA', 50, 4),
('Bruno Henrique', 'ATA', 27, 4),
('Samuel Lino', 'ATA', 16, 4),
('Rafael', 'GOL', 23, 5),
('Ferraresi', 'ZAG', 28, 5),
('Alan Franco', 'ZAG', 32, 5),
('Sabino', 'ZAG', 35, 5),
('Cédric Soares', 'LAT', 6, 5),
('Bobadilla', 'MEI', 21, 5),
('Marcos Antônio', 'MEI', 20, 5),
('Rodriguinho', 'MEI', 15, 5),
('Enzo Díaz', 'LAT', 13, 5),
('Luciano', 'ATA', 10, 5),
('André Silva', 'ATA', 17, 5),
('Gabriel Brazão', 'GOL', 1, 6),
('Mayke', 'LAT', 2, 6),
('Luisão', 'ZAG', 3, 6),
('Luan Peres', 'ZAG', 4, 6),
('Souza', 'LAT', 6, 6),
('João Schmidt', 'MEI', 8, 6),
('Gabriel Bontempo', 'MEI', 7, 6),
('Rollheiser', 'MEI', 10, 6),
('Guilherme', 'ATA', 9, 6),
('Barreal', 'ATA', 11, 6),
('Tiquinho Soares', 'ATA', 19, 6),
('Gabriel', 'GOL', 1, 7),
('Matheus Alexandre', 'LAT', 22, 7),
('Rafael Thyere', 'ZAG', 3, 7),
('Ramon Menezes', 'ZAG', 13, 7),
('Igor Cariús', 'LAT', 6, 7),
('Rivera', 'MEI', 8, 7),
('Zé Lucas', 'MEI', 10, 7),
('Lucas Lima', 'MEI', 25, 7),
('Léo Pereira', 'ATA', 27, 7),
('Matheusinho', 'ATA', 18, 7),
('Derik Lacerda', 'ATA', 9, 7),
('Cássio', 'GOL', 1, 8),
('William', 'LAT', 2, 8),
('Fabrício Bruno', 'ZAG', 3, 8),
('Villalba', 'ZAG', 4, 8),
('Kaiki Bruno', 'LAT', 6, 8),
('Lucas Romero', 'MEI', 8, 8),
('Lucas Silva', 'MEI', 10, 8),
('Christian', 'MEI', 14, 8),
('Matheus Pereira', 'ATA', 30, 8),
('Wanderson', 'ATA', 11, 8),
('Kaio Jorge', 'ATA', 9, 8),
('Ronaldo', 'GOL', 1, 9),
('Santiago Arias', 'LAT', 2, 9),
('David Duarte', 'ZAG', 3, 9),
('Ramos Mingo', 'ZAG', 4, 9),
('Luciano Juba', 'LAT', 6, 9),
('Caio Alexandre', 'MEI', 8, 9),
('Jean Lucas', 'MEI', 10, 9),
('Everton Ribeiro', 'MEI', 7, 9),
('Ademir', 'ATA', 9, 9),
('Kayky', 'ATA', 11, 9),
('Willian José', 'ATA', 19, 9),
('Bruno Ferreira', 'GOL', 1, 10),
('Fabiano Souza', 'LAT', 2, 10),
('Marllon', 'ZAG', 3, 10),
('Willian Machado', 'ZAG', 23, 10),
('Matheus Bahia', 'LAT', 79, 10),
('Dieguinho', 'MEI', 20, 10),
('Richardson', 'MEI', 26, 10),
('Fernando Sobral', 'MEI', 88, 10),
('Galeano', 'ATA', 27, 10),
('Aylon', 'ATA', 11, 10),
('Pedro Raul', 'ATA', 9, 10),


('Lucas Aracanjo', 'GOL', 1,11),
('Raúl Cáceres', 'LAT', 2, 11),
('Lucas Halter', 'ZAG', 3, 11),
('Zé Marcos', 'ZAG', 4, 11),
('Jamerson', 'LAT', 6, 11),
('Gabriel Baralhas', 'MEI', 8, 11),
('Ronald', 'MEI', 29, 11),
('Matheuzinho', 'MEI', 86, 11),
('Fabri', 'ATA', 45,11),
('Lucas Braga', 'ATA', 20,11),
('Renato Kayzer', 'ATA', 10, 11),
('Hugo Souza', 'GOL', 1, 12),
('Matheuzinho', 'LAT', 23, 12),
('André Ramalho', 'ZAG', 4, 12),
('Gustavo Henrique', 'ZAG', 3, 12),
('Matheus Bidu', 'LAT', 6, 12),
('Raniele', 'MEI', 8, 12),
('José Martínez', 'MEI', 10, 12),
('André Carrillo', 'MEI', 21, 12),
('Rodrigo Garro', 'MEI', 30, 12),
('Memphis Depay', 'ATA', 9, 12),
('Yuri Alberto', 'ATA', 7, 12),
('Lucas Aracanjo', 'GOL', 1, 13),
('Raúl Cáceres', 'LAT', 2, 13),
('Lucas Halter', 'ZAG', 3, 13),
('Zé Marcos', 'ZAG', 4, 13),
('Jamerson', 'LAT', 6, 13),
('Gabriel Baralhas', 'MEI', 8, 13),
('Ronald', 'MEI', 29, 13),
('Matheuzinho', 'MEI', 86, 13),
('Fabri', 'ATA', 45, 13),
('Lucas Braga', 'ATA', 20, 13),
('Renato Kayzer', 'ATA', 10, 13),
('Léo Jardim', 'GOL', 1, 14),
('Paulo Henrique', 'ZAG', 22, 14),
('João Victor', 'ZAG', 38, 14),
('Mauricio Lemos', 'ZAG', 4, 14),
('Lucas Piton', 'ZAG', 6, 14),
('Hugo Moura', 'MEI', 25, 14),
('Tchê Tchê', 'MEI', 3, 14),
('Coutinho', 'MEI', 11, 14),
('Nuno Moreira', 'MEI', 17, 14),
('David', 'ATA', 7, 14),
('Pablo Vegetti', 'ATA', 99, 14),
('Jandrei', 'GOL', 13, 15 ),
('Reginaldo', 'ZAG', 93, 15 ),
('Abner', 'ZAG', 23, 15 ),
('Wilker Ángel', 'ZAG', 4, 15 ),
('Marcelo Hermes', 'ZAG', 22, 15 ),
('Caíque', 'MEI', 95,  15),
('Jadson', 'MEI', 16, 15 ),
('Mandaca', 'MEI', 44,  15),
('Gabriel Veron', 'ATA', 7, 15),
('Ênio', 'ATA', 97, 15),
('Gabriel Taliari', 'ATA', 19, 15),
('Tiago Volpi', 'GOL', 1, 16),
('Ronald', 'LAT', 8, 16),
('Fabián Balbuena', 'ZAG', 13, 16),
('Wagner Leonardo', 'ZAG', 3, 16),
('Marlon', 'LAT', 6, 16),
('Dodi', 'MEI', 5, 16),
('Carlos Cuéllar', 'MEI', 14, 16),
('Edenílson', 'MEI', 8, 16),
('Cristian Olivera', 'ATA', 19,16  ),
('Alysson', 'ATA', 20,16  ),
('Carlos Vinicius', 'ATA', 9, 16 ),
('Fábio', 'GOL', 1, 17),
('Júlio Fidelis', 'LAT', 46, 17),
('Davi Schuindt', 'ZAG', 40, 17),
('Manoel', 'ZAG', 26, 17),
('Guga', 'LAT', 23, 17),
('Bernal', 'MEI', 5, 17),
('Nonato', 'MEI', 16, 17),
('Lima', 'MEI', 45, 17),
('Ganso', 'MEI', 10, 17),
('Keno', 'ATA', 11, 17),
('Cano', 'ATA', 14, 17),
('Éverson', 'GOL', 22, 18),
('Natanael', 'LAT', 2, 18),
('Vitor Hugo', 'ZAG', 14, 18),
('Júnior Alonso', 'ZAG', 6, 18),
('Guilherme Arana', 'LAT', 13, 18),
('Alan Franco', 'MEI', 21, 18),
('Alexsander', 'MEI', 5, 18),
('Gustavo Scarpa', 'MEI', 10, 18),
('Tomás Cuello', 'MEI', 28, 18 ),
('Hulk', 'ATA', 7, 18 ),
('Cuello', 'ATA', 28, 18 ),
('Cleiton', 'GOL', 1, 19),
('Guzmán Rodríguez', 'LAT', 2, 19),
('Pedro Henrique', 'ZAG', 14, 19),
('Fabinho', 'ZAG', 5, 19),
('Guilherme Lopes', 'LAT', 31, 19),
('Gabriel', 'MEI', 6,19),
('Eric Ramires', 'MEI', 7, 19 ),
('John John', 'MEI', 10, 19 ),
('Henry Mosquera', 'ATA', 9, 19 ),
('Lucas Barbosa', 'ATA', 8,  19),
('Eduardo Sasha', 'ATA', 35, 19 ),
('João Ricardo', 'GOL', 1, 20 ),
('Eros Mancuso', 'LAT', 14, 20),
('Emanuel Brítez', 'ZAG', 33, 20 ),
('Gastón Ávila', 'ZAG', 3, 20 ),
('Diogo Barbosa', 'LAT', 16,  20),
('Lucas Sasha', 'MEI', 88, 20 ),
('Emmanuel Martínez', 'MEI', 8, 20 ),
('Lucca', 'MEI', 38, 20 ),
('Yago Pikachu', 'ATA', 22, 20 ),
('Breno Lopes', 'ATA', 26,  20),
('Deyverson', 'ATA', 18, 20 );


INSERT INTO partidas (time_casa_id, time_fora_id, data_jogo) VALUES
(15, 1, '2025-08-24'),
(14, 12, '2025-08-24'),
(20, 11, '2025-08-24'),
(8, 3, '2025-08-24'),
(4, 13, '2025-08-25'),
(5, 18, '2025-08-24'),
(9, 6, '2025-08-24'),
(16, 10, '2025-08-23'),
(17, 19, '2025-08-23'),
(2, 7, '2025-08-25');